{
  "hash": "3c13fcbd06022f957f5ddf00bc6bd159",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"qiwenb\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n---\n\n## The question\nFor **Illinois**, I've chosen to examine **median home value** (variable B25077_001). Housing markets vary dramatically across the state, from Chicago's urban core to rural farming counties, but ACS estimates in sparsely populated areas often come with wider margins of error. I want to assess not only where property values are highest, but also which counties' estimates are statistically reliable enough to inform housing policy or investment decisions.\n\n---\n\n## Choosing what to measure\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"IL\"        # two-letter abbreviation, in quotes\nmy_variable <- \"B25077_001\"     # the variable code, in quotes\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 102   5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                       variable   estimate   moe\n  <chr> <chr>                      <chr>         <dbl> <dbl>\n1 17001 Adams County, Illinois     B25077_001   155900  4554\n2 17003 Alexander County, Illinois B25077_001    58700 10578\n3 17005 Bond County, Illinois      B25077_001   133100 13683\n4 17007 Boone County, Illinois     B25077_001   198600  8350\n5 17009 Brown County, Illinois     B25077_001   142200 19435\n6 17011 Bureau County, Illinois    B25077_001   121900  3733\n```\n\n\n:::\n:::\n\n\n\n**Illinois holds 102 counties.**\n\n\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an estimate of 20,000\nthan for an estimate of 200,000. To compare across places, we need it as a\npercentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\n\nNow sort to see which counties are measured least reliably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                       estimate   moe moe_pct\n   <chr>                         <dbl> <dbl>   <dbl>\n 1 Hardin County, Illinois       91700 31269    34.1\n 2 Alexander County, Illinois    58700 10578    18.0\n 3 Jasper County, Illinois      122900 17070    13.9\n 4 Hamilton County, Illinois    108800 15103    13.9\n 5 Brown County, Illinois       142200 19435    13.7\n 6 Calhoun County, Illinois     174000 21433    12.3\n 7 Pulaski County, Illinois      81000  9539    11.8\n 8 Massac County, Illinois      118000 13228    11.2\n 9 Scott County, Illinois       101700 11145    11.0\n10 Bond County, Illinois        133100 13683    10.3\n```\n\n\n:::\n:::\n\n\n\n**Hardin County has the largest margin of error relative to its estimate (34.10%) in Illinois, which is the least reliable**\n\n---\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 3  ~ \"High confidence\",\n    moe_pct < 7 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    21\n2 Low confidence     27\n3 Moderate           54\n```\n\n\n:::\n:::\n\n\n\n**Based on the summary statistics, since the median is 5.27% and the 3rd quartile is 7.09%, the original 3%/6% thresholds would put most counties in \"Moderate\" or \"Low\". As a result, 21 counties are classified as \"High confidence\", 54 as \"Moderate\" and 27 as \"Low confidence\".**\n\n---\n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the same row.\nThat means a **wide** pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                       myvarE myvarM  popE  popM\n  <chr> <chr>                       <dbl>  <dbl> <dbl> <dbl>\n1 17001 Adams County, Illinois     155900   4554 65166    NA\n2 17003 Alexander County, Illinois  58700  10578  5042    NA\n3 17005 Bond County, Illinois      133100  13683 16627    NA\n4 17007 Boone County, Illinois     198600   8350 53316    NA\n5 17009 Brown County, Illinois     142200  19435  6320    NA\n6 17011 Bureau County, Illinois    121900   3733 33027    NA\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 3  ~ \"High confidence\",\n    moe_pct < 7 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         21        514207.\n2 Low confidence          27         11301.\n3 Moderate                54         29429.\n```\n\n\n:::\n:::\n\n\n\n\n**High confidence counties have an average population 45 times larger than Low confidence counties (514,207 vs 11,301), confirming that smaller counties yield less reliable ACS estimates. While 53% of counties are moderately reliable, the 27 Low confidence counties—all sparsely populated—would be risky to use for targeted policy decisions without additional data collection.**\n\n---\n\n## What this means for policy\n\n\n**What: The communities we know the least about in Illinois are its smallest, most rural counties. From my analysis, the 27 Low confidence counties—which include sparsely populated areas like Hardin, Pope, Calhoun, and Gallatin counties—have an average population of just 11,301 residents. These are precisely the places where ACS estimates are most unreliable, yet they represent a significant portion of Illinois's geographic area.**\n\n**Why: The survey is sample‑based, not a census, and reliability depends heavily on sample size. Smaller counties contribute fewer respondents, which produces wider margins of error around every estimate. The ACS's own design prioritizes precision for larger populations, leaving rural communities with statistically noisy data.**\n\n**Who: If a state agency distributing housing grants based on median home values, treating every county's estimate as equally certain. Using the 27 Low confidence counties' numbers at face value could misdirect funds—a county with an artificially high estimate might receive less aid than it actually needs, while another with a low estimate might be overlooked despite hidden poverty. The rural poor, already underserved, would be the ones hurt most.**\n\n---\n\n## Optional challenge: one function, five states\n\nThe county-level pull earlier in this report is hard-coded to one state. I wrapped\nit in a function, `pull_county_reliability()`, that takes a state abbreviation (plus\noptional variable and year) and returns each county's estimate, margin of error,\npopulation, and `moe_pct`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npull_county_reliability <- function(state_abbr, variable = \"B25077_001\", year = 2023) {\n  get_acs(\n    geography = \"county\",\n    variables = c(myvar = variable, pop = \"B01003_001\"),\n    state = state_abbr,\n    year = year,\n    survey = \"acs5\",\n    output = \"wide\"\n  ) %>%\n    transmute(\n      state = state_abbr,\n      GEOID,\n      NAME,\n      estimate = myvarE,\n      moe = myvarM,\n      popE,\n      moe_pct = myvarM / myvarE * 100\n    )\n}\n```\n:::\n\n\nWith `purrr::map_dfr()` the same analysis runs across several states at once. I\npicked five with very different settlement geographies: Illinois, Ohio, Georgia,\nMontana, and Wyoming — 428 counties in total.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstates <- c(\"IL\", \"OH\", \"GA\", \"MT\", \"WY\")\n\nmulti_state <- map_dfr(states, pull_county_reliability)\n\nmulti_state %>%\n  mutate(reliability = case_when(\n    moe_pct < 3  ~ \"High confidence\",\n    moe_pct < 7  ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  )) %>%\n  group_by(state, reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE),\n    .groups = \"drop\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 4\n   state reliability     n_counties avg_population\n   <chr> <chr>                <int>          <dbl>\n 1 GA    High confidence         22        302228.\n 2 GA    Low confidence          93         16234.\n 3 GA    Moderate                44         60540.\n 4 IL    High confidence         21        514207.\n 5 IL    Low confidence          27         11301.\n 6 IL    Moderate                54         29429.\n 7 MT    High confidence          6        112466.\n 8 MT    Low confidence          40          6267.\n 9 MT    Moderate                10         17959.\n10 OH    High confidence         30        302595.\n11 OH    Low confidence          10         26528.\n12 OH    Moderate                48         50769.\n13 WY    High confidence          2         73840.\n14 WY    Low confidence           6          9072.\n15 WY    Moderate                15         25177.\n```\n\n\n:::\n:::\n\n\nTo measure the small-places-are-noisier pattern directly, I correlated county\npopulation (log scale) with `moe_pct` within each state:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmulti_state %>%\n  group_by(state) %>%\n  summarize(correlation = cor(log(popE), moe_pct))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  state correlation\n  <chr>       <dbl>\n1 GA         -0.652\n2 IL         -0.677\n3 MT         -0.637\n4 OH         -0.669\n5 WY         -0.656\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(multi_state, aes(popE, moe_pct, color = state)) +\n  geom_point(alpha = 0.7) +\n  geom_hline(yintercept = 7, linetype = \"dashed\", color = \"grey50\") +\n  scale_x_log10(labels = scales::label_comma()) +\n  labs(\n    title = \"Smaller counties, wider margins of error — in every state\",\n    x = \"County population (log scale)\",\n    y = \"Margin of error as % of estimate\",\n    color = \"State\"\n  )\n```\n\n::: {.cell-output-display}\n![](assignment2_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n**What I found:** the small-places-are-noisier pattern holds everywhere. In all\nfive states the correlation between population and `moe_pct` falls in a narrow band\nbetween -0.64 and -0.68, and the average High-confidence county is anywhere from\n8× (Wyoming) to 45× (Illinois) more populous than the average Low-confidence county.\n\nWhat differs between states is how much of the state is affected. In Montana, 40 of\n56 counties and in Georgia, 93 of 159 fall into Low confidence, while in Ohio only\n10 of 88 do. The *rule* is universal, but its footprint depends on settlement\ngeography: states dominated by small rural counties simply have less trustworthy\nhome-value data overall than states of evenly mid-sized counties like Ohio.\n",
    "supporting": [
      "assignment2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}